dist: trusty
sudo: required
language: go

go_import_path: github.com/ligato/cn-sample-service

go:
  - 1.8.x

cache:
  directories:
    - $HOME/build-cache

before_install:
  - go get -v github.com/golang/lint/golint
  - go get github.com/mattn/goveralls
  - sudo ./vendor/github.com/ligato/vpp-agent/scripts/build-vpp.sh

script:
  - make lint
  - make

after_success:
  - goveralls -coverprofile=/tmp/coverage.out -service=travis-ci
